research_task:
  description: >
    Conduct a thorough research about {github_repo_name} and the {tech_stack}.
    Make sure you find any interesting and relevant information given
    the current year is 2024.
  expected_output: >
    A list with 10 bullet points of the most 
    relevant information about {github_repo_name} and the {tech_stack}.

chapter_writer_task:
  description: >
    Review the context you got and write a table of contents for a technical blog post on {topic} using {tech_stack}
    Ensure the table of contents is well structured and contains all necessary sections.
    Use the {github_repo_name} to find the code examples.
    The table of contents should focus on the code examples using the {tech_stack} for the {topic}
    Reference any links or resources you use to prvide the user with more information.
  expected_output: >
    A table of contents for a technical blog post on {topic} using {tech_stack}
    Formatted as markdown without '```'

blog_post_task:
  description: >
    With the context you got, write a technical blog post on {topic} using {tech_stack}.
    Be sure to stay on topic with the the {tech_stack}
    Use the github repo {github_repo_name} and {tech_stack} to get the code examples.
    Only use this to get the code examples and its examples.
    Ensure the blog post is well structured, contains all necessary sections, and is written in a clear and engaging manner.
    The blog should have primarily based on code examples using the {tech_stack}
    Ensure you use {tech_stack} in the blog post.
    Reference any sources you used to write the blog post to provide the user with more information.
  expected_output: >
    A fully fledge blog post with the main topics, each with a full section of information.
    Formatted as markdown without '```'
  output_file: "output/blog.md"

tweet_writer_task:
  description: >
    With our blog, create a tweet that is engaging and interesting to our audience.
    Ensure the tweet is 280 characters or less.
    Make it catchy and interesting to our audience.
  expected_output: >
    A tweet that is engaging and interesting to our audience.
    Formatted as markdown without '```'
  output_file: "output/tweet.md"
